# Generated by Django 2.1.4 on 2020-05-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordMeans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=32, unique=True)),
                ('means', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'translate_en_2_cn',
            },
        ),
    ]
